title: Cory Pleasance
description: Data Science & AI Student | ML | LLM Research | Systems
theme: jekyll-theme-minimal
url: https://corypleasance.github.io
github:
  username: Cpleasance

# Google Analytics 
google_analytics: G-XXXXXXXXXX
